const express = require("express");
const serverless = require("serverless-http");

const app = express();
const router = express.Router();

const arr = [
  { id: 1, first_name: "Bordie", last_name: "Poundford", position: "Devshare" },
  { id: 2, first_name: "Allina", last_name: "Bannard", position: "Plambee" },
  { id: 3, first_name: "Carol", last_name: "Cayford", position: "Trunyx" },
  { id: 4, first_name: "Baudoin", last_name: "Brideau", position: "Trunyx" },
  { id: 5, first_name: "Shayne", last_name: "Selway", position: "Cogidoo" },
  { id: 6, first_name: "Cliff", last_name: "Rao", position: "Cogidoo" },
  { id: 7, first_name: "Bettye", last_name: "Stainburn", position: "Trunyx" },
  { id: 8, first_name: "Ripley", last_name: "De Simone", position: "Plambee" },
  { id: 9, first_name: "Christin", last_name: "Peterkin", position: "Plambee" },
  { id: 10, first_name: "Pavla", last_name: "Geeve", position: "Devshare" },
  { id: 11, first_name: "Floria", last_name: "Michelotti", position: "Vimbo" },
  { id: 12, first_name: "Dur", last_name: "Brookzie", position: "Cogidoo" },
  {
    id: 13,
    first_name: "Cleavland",
    last_name: "Tender",
    position: "Devshare",
  },
  { id: 14, first_name: "Nissa", last_name: "O'Neal", position: "Devshare" },
  { id: 15, first_name: "Frasquito", last_name: "Peterffy", position: "Vimbo" },
  { id: 16, first_name: "Jareb", last_name: "Breedy", position: "Cogidoo" },
  { id: 17, first_name: "Sharia", last_name: "Dawkins", position: "Plambee" },
  {
    id: 18,
    first_name: "Gwendolen",
    last_name: "Landrean",
    position: "Cogidoo",
  },
  { id: 19, first_name: "Robinet", last_name: "Leming", position: "Devshare" },
  { id: 20, first_name: "Gweneth", last_name: "Hyne", position: "Cogidoo" },
  { id: 21, first_name: "Camile", last_name: "Tapley", position: "Vimbo" },
  { id: 22, first_name: "Tomas", last_name: "Varnam", position: "Plambee" },
  {
    id: 23,
    first_name: "Massimo",
    last_name: "Bennetto",
    position: "Devshare",
  },
  { id: 24, first_name: "Delora", last_name: "Horsey", position: "Trunyx" },
  { id: 25, first_name: "Devlin", last_name: "Aird", position: "Cogidoo" },
  { id: 26, first_name: "Henri", last_name: "Welland", position: "Vimbo" },
  { id: 27, first_name: "Ode", last_name: "Maffione", position: "Jaxspan" },
  { id: 28, first_name: "Terra", last_name: "Graddon", position: "Cogidoo" },
  {
    id: 29,
    first_name: "Whitby",
    last_name: "De Rechter",
    position: "Jaxspan",
  },
  { id: 30, first_name: "Cosette", last_name: "Ayllett", position: "Jaxspan" },
  { id: 31, first_name: "Hartwell", last_name: "Fortune", position: "Vimbo" },
  { id: 32, first_name: "Cally", last_name: "Mc Corley", position: "Cogidoo" },
  { id: 33, first_name: "Brynn", last_name: "Quaife", position: "Devshare" },
  { id: 34, first_name: "Agace", last_name: "Buncom", position: "Vimbo" },
  { id: 35, first_name: "Saraann", last_name: "Espinet", position: "Vimbo" },
  { id: 36, first_name: "Goddard", last_name: "Eastcott", position: "Plambee" },
  { id: 37, first_name: "Niven", last_name: "Carff", position: "Trunyx" },
  { id: 38, first_name: "Melina", last_name: "Sinkins", position: "Cogidoo" },
  { id: 39, first_name: "Gaile", last_name: "Pentland", position: "Plambee" },
  { id: 40, first_name: "Kristopher", last_name: "Lettsom", position: "Vimbo" },
  { id: 41, first_name: "Ariadne", last_name: "Tedman", position: "Cogidoo" },
  { id: 42, first_name: "Tessa", last_name: "Sherrin", position: "Devshare" },
  { id: 43, first_name: "Chryste", last_name: "Twells", position: "Cogidoo" },
  { id: 44, first_name: "Herbie", last_name: "Bere", position: "Vimbo" },
  { id: 45, first_name: "Rory", last_name: "Metcalfe", position: "Trunyx" },
  { id: 46, first_name: "Donnie", last_name: "Labbett", position: "Jaxspan" },
  {
    id: 47,
    first_name: "Mahala",
    last_name: "Attenborrow",
    position: "Devshare",
  },
  { id: 48, first_name: "Padgett", last_name: "Mohun", position: "Trunyx" },
  { id: 49, first_name: "Gabbey", last_name: "Thacke", position: "Jaxspan" },
  { id: 50, first_name: "Noell", last_name: "Visco", position: "Devshare" },
  { id: 51, first_name: "Eben", last_name: "Frigot", position: "Devshare" },
  { id: 52, first_name: "Reeba", last_name: "Crone", position: "Plambee" },
  { id: 53, first_name: "Opalina", last_name: "Roath", position: "Plambee" },
  { id: 54, first_name: "Saba", last_name: "Glazier", position: "Plambee" },
  { id: 55, first_name: "Barr", last_name: "Priscott", position: "Cogidoo" },
  { id: 56, first_name: "Thea", last_name: "De Micoli", position: "Plambee" },
  { id: 57, first_name: "Spence", last_name: "Tonkinson", position: "Trunyx" },
  { id: 58, first_name: "Iain", last_name: "Exall", position: "Jaxspan" },
  { id: 59, first_name: "Conn", last_name: "Castells", position: "Trunyx" },
  { id: 60, first_name: "Odette", last_name: "Mandrier", position: "Plambee" },
  { id: 61, first_name: "Micah", last_name: "Chasney", position: "Devshare" },
  { id: 62, first_name: "Mureil", last_name: "Ranaghan", position: "Cogidoo" },
  { id: 63, first_name: "Tibold", last_name: "Howel", position: "Jaxspan" },
  { id: 64, first_name: "Atalanta", last_name: "Molnar", position: "Devshare" },
  { id: 65, first_name: "Osbert", last_name: "Garber", position: "Plambee" },
  { id: 66, first_name: "Daphna", last_name: "Gerdts", position: "Vimbo" },
  { id: 67, first_name: "Maighdiln", last_name: "Bance", position: "Devshare" },
  { id: 68, first_name: "Ethelda", last_name: "Considine", position: "Vimbo" },
  { id: 69, first_name: "Ebba", last_name: "Isakov", position: "Jaxspan" },
  { id: 70, first_name: "Clifford", last_name: "Gallie", position: "Trunyx" },
  { id: 71, first_name: "Crysta", last_name: "Menure", position: "Vimbo" },
  { id: 72, first_name: "Robert", last_name: "Hartly", position: "Jaxspan" },
  { id: 73, first_name: "Krystal", last_name: "Dowyer", position: "Jaxspan" },
  { id: 74, first_name: "Esra", last_name: "Style", position: "Jaxspan" },
  { id: 75, first_name: "Thorny", last_name: "Giercke", position: "Devshare" },
  { id: 76, first_name: "Pen", last_name: "Hallagan", position: "Jaxspan" },
  { id: 77, first_name: "Salim", last_name: "Sewart", position: "Cogidoo" },
  { id: 78, first_name: "Eileen", last_name: "Proudley", position: "Vimbo" },
  { id: 79, first_name: "Deedee", last_name: "Treherne", position: "Plambee" },
  { id: 80, first_name: "Harwilll", last_name: "Feben", position: "Cogidoo" },
  { id: 81, first_name: "Shaina", last_name: "Niche", position: "Vimbo" },
  { id: 82, first_name: "Jaquenetta", last_name: "Kerner", position: "Trunyx" },
  { id: 83, first_name: "Ranique", last_name: "Sefton", position: "Cogidoo" },
  { id: 84, first_name: "Sim", last_name: "Pinyon", position: "Cogidoo" },
  { id: 85, first_name: "Jania", last_name: "Casham", position: "Trunyx" },
  { id: 86, first_name: "Ezri", last_name: "Colbrun", position: "Vimbo" },
  { id: 87, first_name: "Ellerey", last_name: "Bullick", position: "Cogidoo" },
  { id: 88, first_name: "Novelia", last_name: "Bottle", position: "Cogidoo" },
  { id: 89, first_name: "Renard", last_name: "Cutten", position: "Jaxspan" },
  { id: 90, first_name: "Durward", last_name: "Mallam", position: "Jaxspan" },
  { id: 91, first_name: "Celestina", last_name: "Fey", position: "Cogidoo" },
  { id: 92, first_name: "Genny", last_name: "Scamadin", position: "Jaxspan" },
  {
    id: 93,
    first_name: "Susannah",
    last_name: "Macenzy",
    position: "Devshare",
  },
  { id: 94, first_name: "Phylis", last_name: "Watford", position: "Jaxspan" },
  { id: 95, first_name: "Tory", last_name: "Facchini", position: "Vimbo" },
  { id: 96, first_name: "Wake", last_name: "Brenard", position: "Vimbo" },
  {
    id: 97,
    first_name: "Concordia",
    last_name: "Pointer",
    position: "Devshare",
  },
  { id: 98, first_name: "Ariela", last_name: "Josupeit", position: "Devshare" },
  { id: 99, first_name: "Shell", last_name: "Charville", position: "Cogidoo" },
  {
    id: 100,
    first_name: "Jefferson",
    last_name: "Mattessen",
    position: "Trunyx",
  },
  { id: 101, first_name: "Trix", last_name: "Lovstrom", position: "Jaxspan" },
  { id: 102, first_name: "Jarred", last_name: "Tichner", position: "Jaxspan" },
  { id: 103, first_name: "Lebbie", last_name: "Yemm", position: "Vimbo" },
  { id: 104, first_name: "Wolfy", last_name: "Langlois", position: "Trunyx" },
  { id: 105, first_name: "Julie", last_name: "Winterson", position: "Trunyx" },
  { id: 106, first_name: "Konstantin", last_name: "Gilroy", position: "Vimbo" },
  {
    id: 107,
    first_name: "Essa",
    last_name: "Gillinghams",
    position: "Jaxspan",
  },
  {
    id: 108,
    first_name: "Peyton",
    last_name: "McCafferky",
    position: "Trunyx",
  },
  { id: 109, first_name: "Everett", last_name: "Tester", position: "Cogidoo" },
  { id: 110, first_name: "Lorry", last_name: "Shortell", position: "Trunyx" },
  { id: 111, first_name: "Avery", last_name: "Baline", position: "Plambee" },
  { id: 112, first_name: "Elana", last_name: "Cockhill", position: "Trunyx" },
  {
    id: 113,
    first_name: "Frasquito",
    last_name: "Mellenby",
    position: "Plambee",
  },
  { id: 114, first_name: "Aggi", last_name: "Maryan", position: "Trunyx" },
  {
    id: 115,
    first_name: "Aundrea",
    last_name: "Franzelini",
    position: "Plambee",
  },
  {
    id: 116,
    first_name: "Rebekah",
    last_name: "Fernihough",
    position: "Devshare",
  },
  { id: 117, first_name: "Nanice", last_name: "Lugton", position: "Jaxspan" },
  { id: 118, first_name: "Mick", last_name: "Lapslie", position: "Jaxspan" },
  { id: 119, first_name: "Marge", last_name: "Saladino", position: "Plambee" },
  { id: 120, first_name: "Kristos", last_name: "Paterno", position: "Plambee" },
  { id: 121, first_name: "Marys", last_name: "Aaron", position: "Plambee" },
  {
    id: 122,
    first_name: "Katharina",
    last_name: "Brandenburg",
    position: "Jaxspan",
  },
  { id: 123, first_name: "Haydon", last_name: "De Gouy", position: "Plambee" },
  { id: 124, first_name: "Kay", last_name: "Skirven", position: "Devshare" },
  { id: 125, first_name: "Lelia", last_name: "Repper", position: "Cogidoo" },
  { id: 126, first_name: "Anderson", last_name: "Dear", position: "Trunyx" },
  { id: 127, first_name: "Valera", last_name: "Jeaffreson", position: "Vimbo" },
  { id: 128, first_name: "Mirella", last_name: "Hearnah", position: "Cogidoo" },
  { id: 129, first_name: "Irene", last_name: "Clarey", position: "Trunyx" },
  { id: 130, first_name: "Christos", last_name: "Meldrum", position: "Trunyx" },
  {
    id: 131,
    first_name: "Rubetta",
    last_name: "Martinot",
    position: "Devshare",
  },
  { id: 132, first_name: "Heath", last_name: "Zarfai", position: "Devshare" },
  { id: 133, first_name: "Barbara", last_name: "Rape", position: "Devshare" },
  {
    id: 134,
    first_name: "Xaviera",
    last_name: "Messier",
    position: "Devshare",
  },
  { id: 135, first_name: "Jyoti", last_name: "Barbie", position: "Jaxspan" },
  { id: 136, first_name: "Donaugh", last_name: "Palley", position: "Plambee" },
  { id: 137, first_name: "Elaina", last_name: "Alloway", position: "Cogidoo" },
  { id: 138, first_name: "Abie", last_name: "Rivett", position: "Cogidoo" },
  { id: 139, first_name: "Salmon", last_name: "Roscoe", position: "Plambee" },
  { id: 140, first_name: "Tova", last_name: "Tarver", position: "Trunyx" },
  { id: 141, first_name: "Hali", last_name: "Bysaker", position: "Plambee" },
  { id: 142, first_name: "Zackariah", last_name: "Walsh", position: "Jaxspan" },
  { id: 143, first_name: "Adelind", last_name: "Bony", position: "Jaxspan" },
  {
    id: 144,
    first_name: "Desmund",
    last_name: "Klezmski",
    position: "Devshare",
  },
  { id: 145, first_name: "Marta", last_name: "Schachter", position: "Vimbo" },
  { id: 146, first_name: "Bev", last_name: "Bedells", position: "Trunyx" },
  { id: 147, first_name: "Andy", last_name: "Dalbey", position: "Vimbo" },
  { id: 148, first_name: "Zahara", last_name: "Jennens", position: "Trunyx" },
  { id: 149, first_name: "Gerianne", last_name: "Cheel", position: "Vimbo" },
  {
    id: 150,
    first_name: "Fletcher",
    last_name: "Waddams",
    position: "Jaxspan",
  },
  { id: 151, first_name: "Buddie", last_name: "Frohock", position: "Cogidoo" },
  { id: 152, first_name: "Simeon", last_name: "Wassung", position: "Plambee" },
  { id: 153, first_name: "Jeremy", last_name: "Lear", position: "Jaxspan" },
  {
    id: 154,
    first_name: "Charmion",
    last_name: "Stembridge",
    position: "Devshare",
  },
  { id: 155, first_name: "Perceval", last_name: "Tegler", position: "Vimbo" },
  { id: 156, first_name: "Em", last_name: "Risborough", position: "Plambee" },
  { id: 157, first_name: "Maryanne", last_name: "Roke", position: "Plambee" },
  { id: 158, first_name: "Perl", last_name: "Feely", position: "Plambee" },
  { id: 159, first_name: "Kala", last_name: "Edelheit", position: "Devshare" },
  {
    id: 160,
    first_name: "Emiline",
    last_name: "Merrien",
    position: "Devshare",
  },
  { id: 161, first_name: "Livvy", last_name: "Mallam", position: "Cogidoo" },
  { id: 162, first_name: "Berna", last_name: "Kornel", position: "Trunyx" },
  { id: 163, first_name: "Merna", last_name: "Glading", position: "Devshare" },
  { id: 164, first_name: "Moshe", last_name: "Boness", position: "Vimbo" },
  { id: 165, first_name: "Bailey", last_name: "Folker", position: "Plambee" },
  { id: 166, first_name: "Leigha", last_name: "Relf", position: "Jaxspan" },
  { id: 167, first_name: "Virgie", last_name: "Windress", position: "Vimbo" },
  { id: 168, first_name: "Lyn", last_name: "Hellyar", position: "Jaxspan" },
  { id: 169, first_name: "Towney", last_name: "Veness", position: "Trunyx" },
  { id: 170, first_name: "Betty", last_name: "Brassill", position: "Plambee" },
  { id: 171, first_name: "Gareth", last_name: "McTurk", position: "Vimbo" },
  { id: 172, first_name: "Saba", last_name: "Bockmann", position: "Trunyx" },
  { id: 173, first_name: "Selle", last_name: "Assiter", position: "Jaxspan" },
  { id: 174, first_name: "Brodie", last_name: "Harryman", position: "Cogidoo" },
  { id: 175, first_name: "Juli", last_name: "Ridde", position: "Cogidoo" },
  { id: 176, first_name: "Pamella", last_name: "Tozer", position: "Vimbo" },
  {
    id: 177,
    first_name: "Jeromy",
    last_name: "Hardiker",
    position: "Devshare",
  },
  { id: 178, first_name: "Simonne", last_name: "Gethins", position: "Jaxspan" },
  { id: 179, first_name: "Franklin", last_name: "Isaacs", position: "Cogidoo" },
  {
    id: 180,
    first_name: "Carleen",
    last_name: "Gallaher",
    position: "Devshare",
  },
  {
    id: 181,
    first_name: "Carrissa",
    last_name: "Wheelton",
    position: "Cogidoo",
  },
  { id: 182, first_name: "Herbie", last_name: "Hemerijk", position: "Cogidoo" },
  { id: 183, first_name: "Breanne", last_name: "Warham", position: "Plambee" },
  { id: 184, first_name: "Jaine", last_name: "Krimmer", position: "Jaxspan" },
  { id: 185, first_name: "Ddene", last_name: "Braddick", position: "Cogidoo" },
  { id: 186, first_name: "Celia", last_name: "Wheadon", position: "Trunyx" },
  { id: 187, first_name: "Saxe", last_name: "Fosh", position: "Cogidoo" },
  { id: 188, first_name: "Eachelle", last_name: "Georges", position: "Vimbo" },
  { id: 189, first_name: "Elora", last_name: "Thulborn", position: "Plambee" },
  { id: 190, first_name: "Fedora", last_name: "Harbach", position: "Trunyx" },
  {
    id: 191,
    first_name: "Keene",
    last_name: "Mc Gaughey",
    position: "Cogidoo",
  },
  { id: 192, first_name: "Dirk", last_name: "Pods", position: "Jaxspan" },
  { id: 193, first_name: "Robbie", last_name: "MacKaig", position: "Jaxspan" },
  { id: 194, first_name: "Oralla", last_name: "Brant", position: "Vimbo" },
  { id: 195, first_name: "Rhys", last_name: "Billin", position: "Devshare" },
  { id: 196, first_name: "Keslie", last_name: "Pardy", position: "Vimbo" },
  { id: 197, first_name: "Quinn", last_name: "McRoberts", position: "Jaxspan" },
  { id: 198, first_name: "Antone", last_name: "Behnke", position: "Cogidoo" },
  { id: 199, first_name: "Tara", last_name: "Knapper", position: "Cogidoo" },
  { id: 200, first_name: "Dicky", last_name: "Leeburne", position: "Trunyx" },
  { id: 201, first_name: "Eolande", last_name: "Redhole", position: "Cogidoo" },
  {
    id: 202,
    first_name: "Katleen",
    last_name: "Kinlock",
    position: "Devshare",
  },
  { id: 203, first_name: "Morgan", last_name: "Fryer", position: "Cogidoo" },
  { id: 204, first_name: "Lenci", last_name: "Lanktree", position: "Trunyx" },
  { id: 205, first_name: "Udale", last_name: "Woollett", position: "Jaxspan" },
  {
    id: 206,
    first_name: "Margarethe",
    last_name: "Sprowles",
    position: "Vimbo",
  },
  { id: 207, first_name: "Lanie", last_name: "Harry", position: "Plambee" },
  { id: 208, first_name: "Allin", last_name: "People", position: "Plambee" },
  { id: 209, first_name: "Hamid", last_name: "Muscott", position: "Devshare" },
  { id: 210, first_name: "Catarina", last_name: "Deesly", position: "Jaxspan" },
  {
    id: 211,
    first_name: "Merwyn",
    last_name: "Brakespear",
    position: "Devshare",
  },
  { id: 212, first_name: "Ralph", last_name: "Buckie", position: "Vimbo" },
  { id: 213, first_name: "Arte", last_name: "Bolsover", position: "Vimbo" },
  { id: 214, first_name: "Ario", last_name: "Bickle", position: "Cogidoo" },
  { id: 215, first_name: "Carin", last_name: "Saylor", position: "Vimbo" },
  { id: 216, first_name: "Annalise", last_name: "Lazare", position: "Jaxspan" },
  { id: 217, first_name: "Kelly", last_name: "Burrass", position: "Trunyx" },
  { id: 218, first_name: "Rik", last_name: "Crossan", position: "Trunyx" },
  { id: 219, first_name: "Clarette", last_name: "Salman", position: "Vimbo" },
  { id: 220, first_name: "Fancy", last_name: "Waghorne", position: "Vimbo" },
  {
    id: 221,
    first_name: "Philipa",
    last_name: "Noseworthy",
    position: "Jaxspan",
  },
  { id: 222, first_name: "Nathalia", last_name: "Tubbs", position: "Vimbo" },
  {
    id: 223,
    first_name: "Chantal",
    last_name: "Rosenblad",
    position: "Trunyx",
  },
  { id: 224, first_name: "Symon", last_name: "Eilhart", position: "Cogidoo" },
  { id: 225, first_name: "King", last_name: "Baunton", position: "Cogidoo" },
  { id: 226, first_name: "Kylie", last_name: "Wittier", position: "Trunyx" },
  { id: 227, first_name: "Niall", last_name: "MacEntee", position: "Cogidoo" },
  { id: 228, first_name: "Jill", last_name: "Mariot", position: "Vimbo" },
  {
    id: 229,
    first_name: "Myrwyn",
    last_name: "Bertwistle",
    position: "Trunyx",
  },
  { id: 230, first_name: "Christiano", last_name: "Pecey", position: "Trunyx" },
  { id: 231, first_name: "Aleen", last_name: "Sturm", position: "Jaxspan" },
  { id: 232, first_name: "Bertina", last_name: "Norrie", position: "Plambee" },
  { id: 233, first_name: "Manya", last_name: "Dowry", position: "Trunyx" },
  { id: 234, first_name: "Tabby", last_name: "Taysbil", position: "Trunyx" },
  {
    id: 235,
    first_name: "Dehlia",
    last_name: "Flintiff",
    position: "Devshare",
  },
  { id: 236, first_name: "Justinian", last_name: "Cumes", position: "Cogidoo" },
  { id: 237, first_name: "Ki", last_name: "Fillery", position: "Jaxspan" },
  {
    id: 238,
    first_name: "Farlee",
    last_name: "de Savery",
    position: "Devshare",
  },
  { id: 239, first_name: "Odele", last_name: "Sagg", position: "Plambee" },
  { id: 240, first_name: "Andi", last_name: "Corke", position: "Trunyx" },
  { id: 241, first_name: "Lily", last_name: "Jays", position: "Devshare" },
  { id: 242, first_name: "Doroteya", last_name: "Ellinor", position: "Trunyx" },
  { id: 243, first_name: "Carolin", last_name: "Ridings", position: "Vimbo" },
  { id: 244, first_name: "Iolanthe", last_name: "Brann", position: "Jaxspan" },
  {
    id: 245,
    first_name: "Bendicty",
    last_name: "Gilpillan",
    position: "Devshare",
  },
  { id: 246, first_name: "Brenna", last_name: "Bubear", position: "Plambee" },
  { id: 247, first_name: "Carlos", last_name: "Hunstone", position: "Plambee" },
  { id: 248, first_name: "Kare", last_name: "Eustace", position: "Jaxspan" },
  { id: 249, first_name: "Malia", last_name: "Sansbury", position: "Devshare" },
  { id: 250, first_name: "Reeba", last_name: "Lillyman", position: "Trunyx" },
  { id: 251, first_name: "Cicely", last_name: "Spear", position: "Jaxspan" },
  { id: 252, first_name: "Paola", last_name: "Crick", position: "Jaxspan" },
  {
    id: 253,
    first_name: "Marguerite",
    last_name: "Scripps",
    position: "Vimbo",
  },
  { id: 254, first_name: "Bobbe", last_name: "Shaddick", position: "Cogidoo" },
  { id: 255, first_name: "Willi", last_name: "Campany", position: "Cogidoo" },
  { id: 256, first_name: "Valeria", last_name: "Tondeur", position: "Cogidoo" },
  { id: 257, first_name: "Harald", last_name: "Ainscow", position: "Devshare" },
  { id: 258, first_name: "Karol", last_name: "Hargerie", position: "Vimbo" },
  {
    id: 259,
    first_name: "Jamison",
    last_name: "Jedraszczyk",
    position: "Trunyx",
  },
  { id: 260, first_name: "Katy", last_name: "Brumfitt", position: "Vimbo" },
  { id: 261, first_name: "Roberto", last_name: "MacDonald", position: "Vimbo" },
  { id: 262, first_name: "Britt", last_name: "Boxall", position: "Jaxspan" },
  { id: 263, first_name: "Euell", last_name: "Brende", position: "Trunyx" },
  { id: 264, first_name: "Rog", last_name: "Duddy", position: "Cogidoo" },
  {
    id: 265,
    first_name: "Purcell",
    last_name: "Nystrom",
    position: "Devshare",
  },
  { id: 266, first_name: "Mervin", last_name: "Tant", position: "Devshare" },
  { id: 267, first_name: "Tracy", last_name: "Currer", position: "Jaxspan" },
  { id: 268, first_name: "Carlee", last_name: "Bartocci", position: "Jaxspan" },
  { id: 269, first_name: "Suzanna", last_name: "Hincks", position: "Plambee" },
  { id: 270, first_name: "Heather", last_name: "Downse", position: "Devshare" },
  { id: 271, first_name: "Elbert", last_name: "Kryszka", position: "Devshare" },
  { id: 272, first_name: "Camile", last_name: "Raggles", position: "Vimbo" },
  {
    id: 273,
    first_name: "Cassaundra",
    last_name: "McDonell",
    position: "Cogidoo",
  },
  { id: 274, first_name: "Raye", last_name: "Poley", position: "Plambee" },
  { id: 275, first_name: "Kliment", last_name: "Ioan", position: "Devshare" },
  { id: 276, first_name: "Carlee", last_name: "Harvatt", position: "Jaxspan" },
  {
    id: 277,
    first_name: "Bronnie",
    last_name: "Van der Kruis",
    position: "Plambee",
  },
  { id: 278, first_name: "Sydney", last_name: "Ivimy", position: "Trunyx" },
  { id: 279, first_name: "Chiquia", last_name: "O'Logan", position: "Trunyx" },
  { id: 280, first_name: "Dane", last_name: "Kempe", position: "Devshare" },
  { id: 281, first_name: "Layney", last_name: "Lafrentz", position: "Jaxspan" },
  { id: 282, first_name: "Tori", last_name: "Copnall", position: "Plambee" },
  { id: 283, first_name: "Sloane", last_name: "Karlsson", position: "Plambee" },
  {
    id: 284,
    first_name: "Hildegaard",
    last_name: "Gini",
    position: "Devshare",
  },
  { id: 285, first_name: "Kilian", last_name: "McCoy", position: "Plambee" },
  { id: 286, first_name: "Rivkah", last_name: "Elcoate", position: "Jaxspan" },
  { id: 287, first_name: "Abigael", last_name: "Thirtle", position: "Jaxspan" },
  { id: 288, first_name: "Dorise", last_name: "Doyley", position: "Jaxspan" },
  { id: 289, first_name: "Robinet", last_name: "Gimbart", position: "Trunyx" },
  { id: 290, first_name: "Alister", last_name: "Maly", position: "Plambee" },
  {
    id: 291,
    first_name: "Mariquilla",
    last_name: "Hambatch",
    position: "Vimbo",
  },
  { id: 292, first_name: "Kipp", last_name: "Drennan", position: "Trunyx" },
  {
    id: 293,
    first_name: "Georgine",
    last_name: "Calendar",
    position: "Cogidoo",
  },
  { id: 294, first_name: "Garrot", last_name: "Cicco", position: "Plambee" },
  { id: 295, first_name: "Rene", last_name: "Dagleas", position: "Cogidoo" },
  { id: 296, first_name: "Dotty", last_name: "Hawton", position: "Plambee" },
  { id: 297, first_name: "Kaylee", last_name: "Pettwood", position: "Trunyx" },
  { id: 298, first_name: "Hans", last_name: "Guiso", position: "Devshare" },
  {
    id: 299,
    first_name: "Basilius",
    last_name: "Ziemecki",
    position: "Plambee",
  },
  { id: 300, first_name: "Duff", last_name: "Cope", position: "Cogidoo" },
];
var cors = require("cors");

router.get("/cards", cors(), (req, res) => {
  res.json(arr);
});

app.use(`/.netlify/functions/api`, router);

module.exports = app;
module.exports.handler = serverless(app);
